= Timbuctoo Elastic Search Indexer
A tool that autmatically updates the Elastic Search indices used by data sets in Timbuctoo.

== Development

Run both commands from the root directory of the project.

=== Compilation of Type script

`tsc -w`

=== Running the tool

`nodemon dist/**`

=== Other prerequisites
Make sure:
* You have a version of https://github.com/HuygensING/timbuctoo[Timbuctoo] running and follow the "Getting Started" from the `README.adoc`.
* You have Elasticsearch running
  ** For example with docker: https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
    *** This project uses:

....
  docker pull docker.elastic.co/elasticsearch/elasticsearch:5.5.2
  docker run -p 9200:9200 -e "http.host=0.0.0.0" -e "transport.host=127.0.0.1" docker.elastic.co/elasticsearch/elasticsearch:5.5.2
....

=== Add dependencies
`yarn add {name of the dependency} --dev` 
install all dependencies: `yarn install`

=== Test requests
To test the tool we use https://insomnia.rest/[Insomnia].
The requests can be imported from `insomniarequests.json`.


== TODO
* Elastic search indexer
        ** Default config kunnen serveren aan de Timbuctoo front-end:
....
  http://timbuctoo.huygens.knaw.nl/datatypes/person-name {
          possibleFacetTypes : [ MultiSelect, bla ]
          fullTextPossible: true
  }
  *: {
          possibleFacetTypes : [ MultiSelect, bla ]
          fullTextPossible: true
  }
....
        ** Ophalen index config async
        ** Ophalen index config via graphql
                *** 50 diep
        ** Dependencies voor runtime ook als runtime dep toevoegen
        ** In Timbuctoo reindex ping toevoegen

